apiVersion: apps/v1
kind: Deployment

metadata:
  name: enterprise-app
  namespace: enterprise

spec:
  replicas: 2

  selector:
    matchLabels:
      app: enterprise

  template:
    metadata:
      labels:
        app: enterprise

    spec:
      containers:
        - name: app
          image: 705557196379.dkr.ecr.us-east-1.amazonaws.com/enterprise-devops:82aa70a662154503d364c356d7be063d73e6a7fa

          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: username

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: password