sonar.projectKey=enterprise-devops
sonar.projectName=enterprise-devops
sonar.sourceEncoding=UTF-8

# Scan the application code
sonar.sources=app

# Exclude dependencies
sonar.exclusions=**/node_modules/**,**/dist/**
