############################################################
# Namespace
############################################################

############################################################
# Replica Count
############################################################

replicaCount: 3

############################################################
# Image
############################################################

image:
  repository: 705557196379.dkr.ecr.us-east-1.amazonaws.com/enterprise-devops
  tag: 82aa70a662154503d364c356d7be063d73e6a7fa
  pullPolicy: Always

############################################################
# Service
############################################################

service:
  type: LoadBalancer
  port: 80
  targetPort: 3000

############################################################
# Resources
############################################################

resources:
  requests:
    cpu: "250m"
    memory: "256Mi"

  limits:
    cpu: "500m"
    memory: "512Mi"

############################################################
# ConfigMap
############################################################

config:
  APP_NAME: "Enterprise DevOps Capstone"
  ENVIRONMENT: "Development"

############################################################
# Secret
############################################################

secret:
  name: enterprise-devops-secret

############################################################
# Health Probes
############################################################

probes:
  path: /
  port: 3000
  readinessDelay: 10
  livenessDelay: 30
