apiVersion: v1
kind: ConfigMap

metadata:
  name: enterprise-config

  namespace: enterprise-devops

data:

  APP_NAME: "Enterprise DevOps"

  ENVIRONMENT: "development"

  LOG_LEVEL: "INFO"

  PORT: "3000"
