name: Continuous Integration

on:
  push:
    branches:
      - feature/terraform
      - main

  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: app

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Packages
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Build Application
        run: npm run build

      - name: SonarQube Scan
        shell: cmd
        working-directory: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          sonar-scanner ^
            -Dsonar.projectKey=enterprise-devops ^
            -Dsonar.projectName=enterprise-devops ^
            -Dsonar.sources=app/src ^
            -Dsonar.tests=app/tests ^
            -Dsonar.sourceEncoding=UTF-8 ^
            -Dsonar.host.url=%SONAR_HOST_URL% ^
            -Dsonar.token=%SONAR_TOKEN%

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: application
          path: app/
